### ISSUE TITLE
Not able Receive data

### ISSUE THREAD

**Issue by newDroidGuy** [davidepedranz/AndWeight#2]
I have paired the UC-351PBT-Ci with android samsung galaxy tab 2, after running the app and clicking 'Start Service' and taking measurements in device nothing is updated in the app.

**Comment by davidepedranz** [comment]
Hi,

I guess it could be a problem with the pairing. I remember having troubles with it the first times (I had to try repeatedly to get it right. The following helped me making the communication working:
 * Close the app
 * Unpair the device from Android's settings
 * Pair the device again (remove the batteries, wait 3-5 seconds, reinsert the batteries, start immediately the Bluetooth search from Android)
 * The device should show "Pr" on the display
 * Start the app, click "Start Service"
 * Take a measure with the scale

In the pairing process, the device "saves" the MAC address of the smartphone/tablet. When you start the service, it starts a ListenThread which listens for incoming Bluetooth connections from a device with UUID "00001101-0000-1000-8000-00805F9B34FB".

I found this value searching a lot on the web. I tried different ones but it was not working. I hope it is the same for every UC-351PBT-Ci device. We had about 10-15 of them and it worked with all of them.

If it still does not work, I would try with another smartphone/tablet.

I hope this can help!

**Comment by vidyajejurkar** [comment]
davidepedranz:having problem with  UC-351PBT-Ci ..i am not able to parse data.but that application is working for  UC-321PBT-Ci.is there any new parsing method for  UC-351PBT-Ci????
plz help

**Comment by davidepedranz** [comment]
I don't understand your question... My app is working with the model UC-351PBT-Ci using SPP profile. I have no idea how the UC-321PBT-Ci is working. It seems to me to remember that model, maybe there is another project on GitHub for that.

**Comment by vidyajejurkar** [comment]
is there any modification in protocol for latest weightscale like UC-351PBT-Ci

**Comment by davidepedranz** [comment]
I have no idea, I am sorry. You maybe could try to contact A&D to get the specification for your scale.

**Comment by vidyajejurkar** [comment]
i get this packet e7000030002e1001010100280000ffffffff0d1f001ef0000001000100160001000100100001000cfe0013ce2016042215230600

cfe0013ce(50.70) shows weight...bt get constant weight for each time...
i did something like below in my code plz check:

if (data[18] == (byte) 0x0d
									&& data[19] == (byte) 0x1f) // fixed report
							{
								System.out.println("0d && 1E:");
								count = 3;
								// set invoke id so get correct response
								invoke = new byte[] { data[6], data[7] };
								// write back response
								(new WriteThread(mFd)).start();

								// parse data!!

								if (data[3] == (byte) 0x3a) {

									String pr = test.substring(84, 88);
									System.out.println("PARSING weight :" + pr);
									Log.i("PARSING weight :", "" + pr);
									int weight = Integer.parseInt(pr, 16);

									Log.i("PARSING weight :", "" + weight);
									System.out.println("PARSING weight :"
											+ weight);
									sendMessage(RECEIVED_SYS, weight);
								}

**Comment by vidyajejurkar** [comment]
can u plz share ur link for spp

**Comment by davidepedranz** [comment]
Can you send me your email? Sorry for the delay.

**Comment by vidyajejurkar** [comment]
@davidepedranz:

did u worked on BLE Weightscale.???
if yes plz  send me useful link .

**Comment by davidepedranz** [comment]
If you mean HDP (IEEE 11073), no I tried, found and failed.

Useful links for that, a project on GitHub for another weight scale model: https://github.com/nunoar/Android-HDP-AND-UC-321PBT-C-Precision-Health-Scale/tree/develop

**Comment by vidyajejurkar** [comment]
No Not IEEE 11073. i am talking about  Bluetooth Low Enery  for Weight Scale

**Comment by davidepedranz** [comment]
No, I have not worked with it, sorry.
